import os, glob

# The following 8 arrays contain the extracted compile-time 
# configuration options from the x264 using the "./configure --help"
external_libraries = ["--disable%s" % p for p in ("-avs", 
                                                "-swscale",
                                                "-lavf",
                                                "-ffms",
                                                "-gpac",
                                                "-lsmash"
                                                )]              
advanced_options = ["--enable%s" % p for p in ("-lto", 
                                            "-debug", 
                                            "-gprof",
                                            "-strip",
                                            "-pic"
                                            ) ]
advanced_options_2 = ["--disable-asm"]
configuration_options = ["--enable%s" % p for p in ("-shared", 
                                            "-static", 
                                            "-bashcompletion"
                                            ) ]
configuration_options_2 = ["--disable%s" % p for p in ("-cli",
                                            "-bashcompletion", 
                                            "-opencl", 
                                            "-gpl",
                                            "-thread",
                                            "-win32thread",
                                            "-interlaced"
                                            ) ]
configuration_options_3 = ["--system-libx264"]
configuration_options_4 = ["--bit-depth=%s" % p for p in ("8", 
                                            "10", 
                                            "all"
                                            ) ]
configuration_options_5 = ["--chroma-format=%s" % p for p in ("400", 
                                            "420", 
                                            "422",
                                            "444",
                                            "all"
                                            ) ] # 23/2

# Adding the single configurations to an array 
def extractDigits(lst):
    res = []
    for el in lst:
        sub = el.split(', ')
        res.append(sub)
    print(res)
    return(res)
   

# All single configurations                   
single_configurations_01 = extractDigits(external_libraries)
single_configurations_02 = extractDigits(advanced_options)
single_configurations_03 = extractDigits(advanced_options_2)
single_configurations_04 = extractDigits(configuration_options)
single_configurations_05 = extractDigits(configuration_options_2)
single_configurations_06 = extractDigits(configuration_options_3)
single_configurations_07 = extractDigits(configuration_options_4)
single_configurations_08 = extractDigits(configuration_options_5)

# Adding the sample configuration sets (generated by FeatureIDE) to an array
sample_configurations = []

# for variant in glob.glob("measures/products/*.config"):
for variant in glob.glob("measures/products_27/*.config"):
    lineList = list()
    with open(variant) as f:
        for line in f:
            lineList = [line.rstrip('\n') for line in open(variant)]
        sample_configurations.append(lineList)

print(sample_configurations)

# All single and sample configurations, 
# which will be used to measure the changes on
# the binary size and number of gadgets in x264
all_options =  [*sample_configurations]
all_s_options = [*single_configurations_01,
                *single_configurations_02,
                *single_configurations_03,
                *single_configurations_04,
                *single_configurations_05,
                *single_configurations_06,
                *single_configurations_07,
                *single_configurations_08] 